# Generated by Django 3.1.5 on 2021-12-27 16:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('bookId', models.AutoField(primary_key=True, serialize=False)),
                ('bname', models.CharField(max_length=100)),
                ('bdesc', models.TextField(max_length=200)),
                ('bprize', models.IntegerField()),
                ('plprize', models.IntegerField()),
                ('bsold', models.BooleanField(default=False)),
                ('buser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user')),
            ],
        ),
    ]
