# Generated by Django 3.1.5 on 2022-01-28 10:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0004_auto_20220128_1550'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transactions',
            fields=[
                ('tid', models.AutoField(primary_key=True, serialize=False)),
                ('transactionId', models.CharField(max_length=10)),
                ('tamount', models.IntegerField()),
                ('tdate', models.DateTimeField(auto_now_add=True)),
                ('exchangeType', models.CharField(max_length=10)),
                ('fromUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fromUser', to='user.user')),
                ('toUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='toUser', to='user.user')),
            ],
        ),
    ]
