# Generated by Django 3.1.5 on 2021-12-27 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('uid', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('uname', models.CharField(max_length=30)),
                ('uphone', models.CharField(max_length=13)),
                ('password', models.CharField(max_length=100)),
            ],
        ),
    ]
