# Generated by Django 3.1.5 on 2022-01-28 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_user_userimg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='userImg',
            field=models.ImageField(upload_to=''),
        ),
    ]
